# https://ci.appveyor.com/project/OpenWaterAnalytics/stormwater-management-model

matrix:
  fast_finish: true

environment:
  global:
    # Environment variables used by astropy helpers
    PYTHON: "C:\\conda"
    CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\ci-helpers\\appveyor\\windows_sdk.cmd"

  matrix:
    - PYTHON_VERSION: "3.6"
      PYTHON_ARCH: "32"
      ARCH: "x86"
      platform: "x86"
    - PYTHON_VERSION: "3.6"
      PYTHON_ARCH: "64"
      ARCH: "amd64"
      platform: "x64"
    - PYTHON_VERSION: "3.4"
      PYTHON_ARCH: "32"
      ARCH: "x86"
      platform: "x86"
    - PYTHON_VERSION: "3.4"
      PYTHON_ARCH: "64"
      ARCH: "amd64"
      platform: "x64"

install:
  # Astropy ci-helpers. See https://github.com/astropy/ci-helpers
  - "git clone git://github.com/astropy/ci-helpers.git"
  - "powershell ci-helpers/appveyor/install-miniconda.ps1"
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  # Install dependencies
  - "%CMD_IN_ENV% conda install conda-build anaconda-client -q -y"
  - "%CMD_IN_ENV% conda-build conda.recipe --python %PYTHON_VERSION% --old-build-string"
  - "%CMD_IN_ENV% conda install -n test libswmm --use-local"
  #- "%CMD_IN_ENV% conda create -n format clangdev -c conda-forge"

# Not a .NET project, we build in the install step instead
build: false

test_script:
  # Check file format with clang
  #- "%CMD_IN_ENV% activate format"
  #- "%CMD_IN_ENV% python tools\\clangformatter.py src\\"
  # Test built package
  #- "%CMD_IN_ENV% activate test"
  #- "%CMD_IN_ENV% run-swmm --version"

on_success:
  - "%CMD_IN_ENV% activate root"
  - "%CMD_IN_ENV% python tools\\build_and_upload.py"
